// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgjHNjigS0gsHz3DPoE4vG5I5PI3tYg1o',
    appId: '1:33480415511:web:d829b480cd506a0d277f52',
    messagingSenderId: '33480415511',
    projectId: 'chat-648dd',
    authDomain: 'chat-648dd.firebaseapp.com',
    storageBucket: 'chat-648dd.appspot.com',
    measurementId: 'G-F42GXCT3KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoyqGWmiL9ioOZ2WFNk3DH0f28V-pTiHM',
    appId: '1:33480415511:android:11c8978359bd6ccc277f52',
    messagingSenderId: '33480415511',
    projectId: 'chat-648dd',
    storageBucket: 'chat-648dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCt0bTALsp_g0whN4I0HIfUQnbQFCBNOs',
    appId: '1:33480415511:ios:311fd212df0b5452277f52',
    messagingSenderId: '33480415511',
    projectId: 'chat-648dd',
    storageBucket: 'chat-648dd.appspot.com',
    iosBundleId: 'com.example.shubham4338',
  );
}
